spring:
  # H2
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: ${LOCAL_DB_URL}
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

    # JPA
    jpa:
      defer-datasource-initialization: true
      database-platform: org.hibernate.dialect.H2Dialect
      open-in-view: true
      #generate-ddl : true
      show-sql : true
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          show_sql: true
          format_sql: true

  redis:
    host: localhost
    port: 6379

logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정


jwt:
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret' 이라는 문자열을 base64로 인코딩
  secret:
    key : ${JWT_SECRET_KEY}
  token:
    access-token-expiration-millis: 60000      # 1분 900000(15분)
    refresh-token-expiration-millis: 120000  # 7일 604800000(7일)